### PR TITLE
Implement full color remapper

### PR DESCRIPTION
**Pull request by netpok**
This pull request implements a full five color remapper.

### CODE REVIEW

**Comment by netpok** [comment]
As mentioned in the ardenst tasmota repo: https://github.com/arendst/Sonoff-Tasmota/pull/5326#issuecomment-466811226

Mapping table: https://docs.google.com/spreadsheets/d/1ovEWyUBObOYYAl8ey6K6LffHhiniRXuIq7iivyxmyEU/edit?usp=sharing

**Comment by gsimon75** [comment]
Just for the fun of it, I've sketched up a [plain-C-ish approach](https://pastebin.com/EQV9Ukzs) for the index-to-permutation conversion.

All the dynamic memory operations (vector, array, etc.) could be optimised away, though it is significantly harder to understand what the code does and why is it correct :).

As this conversion happens only at startup and when the param is changed, it is not performance-critical at all, so the readability of the code is more important, and in that aspect your implementation is better than this one.

**Comment by netpok** [comment]
Nice, Is this using less flash? if yes, we should use this.

**Comment by gsimon75** [comment]
I don't think so. Your code uses libstdc++, which is already there, regardless of whether we use it here or not. Besides, I think the code readability is more important than to save a dozen bytes or so.

As you wrote, your code adds only hundred-some bytes, so this one cannot be significantly smaller than that.

**Pull request merged**
