### PR TITLE
Integrate with xdrv_04_light.ino

### PR DESCRIPTION
**Pull request by kueblc**
I've integrated your code into `xdrv_04_light.ino` to bring it in line with our discussion, and seems to work great. There is also a lot less duplicated code. Command processing is handled already, so you can do things like set the color and white levels simultaneously, fade between colors, and use the built in schemes.

I did this by adding to light_type. A new code path takes place if the bit 16 is set. The PWM handling is also duplicated.

I also added a pin for SM16716 select, as is the case in my bulb. This pin is brought HIGH when any of RGB are non-zero, and LOW otherwise.

It is not perfect yet, but I think we are in the final stretch here.

- [x] For code clarity, 16 should probably be replaced with a constant, however I saw a note specifying no light_types are to be added.
- [x] There is a bug with the init process on my bulb, when color is first enabled, the first color command is ineffective. I have been messing with timing and the init sequence, but as of this post I have yet to determine the cause.

### CODE REVIEW

**Comment by gsimon75** [comment]
Thanks for the integration, it **works**  :D !

I checked my bulb for the SELECT signal you mentioned, but mine doesn't seem to have it. Maybe it's present only in the cold+warm white version?

In my cold-white-only version GPIO16, GPIO13 (?reserved for led?) and GPIO2 (?reserved for user switch?) are left unconnected, and GPIO15 is hardwired to GND. If yours has this SELECT on one of 16, 13 or 2, then it may be compatible between the two versions.

If it is, then maybe we should add it to the template 'SYF05' in sonoff_template.h?

As of the instability mentioned by @seidler2547, I'm trying to reproduce it with my bulb, too. After how much time did this reboot occur in your setup?
(Though, if it's caused by some thermal protection, then having it detached from the heatsink may falsify the result and the actual uptime may depend even on the position of the boards. Anyway, we'll see.)

**Comment by kueblc** [comment]
> Thanks for the integration, it **works** :D !

Thrilled to hear it!

> I checked my bulb for the SELECT signal you mentioned, but mine doesn't seem to have it. Maybe it's present only in the cold+warm white version?

My bulb is an RGB + warm white. It uses an SM726EB that's protocol compatible with the SM16716. Warm white is PWM pin 5, while the SM726EB is on 4 and 14 (clock and data). Aside from the select pin, it's identical to yours.

> In my cold-white-only version GPIO16, GPIO13 (?reserved for led?) and GPIO2 (?reserved for user switch?) are left unconnected, and GPIO15 is hardwired to GND. If yours has this SELECT on one of 16, 13 or 2, then it may be compatible between the two versions.
> 
> If it is, then maybe we should add it to the template 'SYF05' in sonoff_template.h?

We're in luck, the select pin is 13!

> As of the instability mentioned by @seidler2547, I'm trying to reproduce it with my bulb, too. After how much time did this reboot occur in your setup?
> (Though, if it's caused by some thermal protection, then having it detached from the heatsink may falsify the result and the actual uptime may depend even on the position of the boards. Anyway, we'll see.)

I think it might be overdrawing current when running both white and color LEDs, as the stock firmware only allows one or the other.

**Comment by kueblc** [comment]
Missed one,

> After how much time did this reboot occur in your setup?

It happens on the order of seconds to a minute after putting the color and white on full. It also reset my configuration (but not the firmware itself!) so something funny is going on in flash.

**Comment by gsimon75** [comment]
I've added the SELECT pin to the SYF05 template, added that '#define USE_SM16716' to my_user_config.h (the code seems usable now).

I agree with you on the current being too high. My bulb now had a 35 min uptime, but then I switched it off as even the heatsink was almost too hot to touch. The LED panel is not yet glued back, so the only thermal coupling with the heatsink is through the air gap, and even so it's abnormally hot. And it's not coming from the LEDs, because that small transformer is even hotter.
I can still touch it, so it can't be hotter than 40 Celsius, but if it builds up so much heat so quickly, then in an enclosed lamp armature it'd definitely overheat.

The whole circuit draws around 37mA from the 230V mains, that's 8.5 Watts, so it's realistic.
I'll need some minutes to measure the LED panel voltage and current, but then we'll have the power consumption of the controller board as well.

**Comment by gsimon75** [comment]
About the power distribution (both color and white leds at maximum, wifi connected):

Input:
-  230V @ 37mA = **8510mW**

Output:
- Color LEDs and their controller chip: 19.6V @ 65.6mA = 1286mW
- White LEDs and their controller chip: 19.6V @ 155.2mA = 3042mW
- TYWE3S module: 3.3V @ 411mA = 1356mW (according to its datasheet)
= total: **5684mW**

Difference: 2826mW
This is the loss of the power supply (so its efficiency is about 66.8%).

I'm no expert in power designs, but googling for heatsinks for 3W, the [ones I found](https://www.addicore.com/3w-LED-heatsink-p/ad270.htm) had significantly larger surface than the one in this bulb.

So please correct me if I'm wrong, but it seems to me that 1) this power supply is a 'cheap' one, and 2) the cooling of the bulb is seriously under-designed.

As I wouldn't really like setting anyones bulb (and house...) on fire, I think it would be a good idea to hardcode some restriction, maybe like the one you found:

> as the stock firmware only allows one or the other

What do you think?

**Comment by kueblc** [comment]
> So please correct me if I'm wrong, but it seems to me that 1) this power supply is a 'cheap' one, and 2) the cooling of the bulb is seriously under-designed.
>
> As I wouldn't really like setting anyones bulb (and house...) on fire, I think it would be a good idea to hardcode some restriction, maybe like the one you found:

That does sound like a safety hazard, I'm not sure what the case may be with other compatible bulbs. I had considered enforcing some limits in firmware but I am hesitant to ban white and color together outright.

Combining the color LEDs with white allows an adjustable color temperature, something above and beyond what the stock firmware offers. It's also useful to have both active during transition effects (which *is* present in the stock firmware) and I imagine it's safe for such a short period of time. With that in mind, at least some degree of interplay should be permitted.

I might try to find out what the limitations are for my bulb and see if I can come up with a nice way to limit the combined power without imposing anymore restrictions than necessary. That will be for tomorrow as it's past midnight here in NY.

Also, I feel we should make this solution as general as possible for other bulbs using compatible chips. For the module template I might prefer to keep pins 12, and 13 user assigned, in case your device lacks the select pin or secondary white.

**Comment by gsimon75** [comment]
> I am hesitant to ban white and color together outright

I agree. This unfortunate design is the property of only this bulb model, and not of the controller chip, so with a more robust cooling and/or a better supply the mixed control indeed would make sense.

> That will be for tomorrow as it's past midnight here in NY.

Good night then :) !
Meanwhile I'll get a thermometer and try to get some more accurate measurements.

In [this discussion](https://community.home-assistant.io/t/cheap-uk-wifi-bulbs-with-tasmota-teardown-help-tywe3s/40508/24) @hatri mentions that he ran this bulb at '70-85 Celsius', so if that's normal, then we still have a some leeway.

I'll compare it with a Sonoff B1, see how hot it gets after an hour or so.

**Pull request merged**
