### PR TITLE
Renamed SM16716 select and added our enhancement to feature list

### PR DESCRIPTION
**Pull request by kueblc**
I used an automated script to pull the translation for "Enable KNX" and plug that back in to say "Enable SM16716" in so many languages. Thus they are only as accurate as D_KNX_ENABLE.

Also noticed that we missed adding our feature to the feature list. This allows us to check from the Status command if our feature was compiled in.

### CODE REVIEW

**Review by gsimon75 — APPROVED** [review]

**Review by gsimon75 — APPROVED** [review]

**Comment by damondins** [comment]
@kueblc  @gsimon75 Well after the merge with the dev branch I can no get White!!!! I still get the flicker on dim and when I go from white to a color it coes to the cool white 1st then i switch colors and then all colors work. So something going from white to color is still kinda off. But I'm happy to be able to get white and color in some fashion. Thanks for all the great work!

**Comment by kueblc** [comment]
@damondins Sorry you're still having issues, I still haven't been able to reproduce the issue with white not working or dimming correctly.

As far as the issue with the first color not working, try adjusting the delay here https://github.com/arendst/Sonoff-Tasmota/blob/development/sonoff/xdrv_04_light.ino#L413 and see if that helps, yours might need a little longer to wake up.

**Comment by damondins** [comment]
@kueblc Ok so I was able to change the code to 500ms and now the light is working as expected with color and white. The dimming still flashes on change with white only but I can live with that. Finally, have a fully functioning bulb thanks to Y'all. Very much appreciated! You may want to update the code so that others may not have that issue. BTW I initially set it to 1000ms and there wasn't any noticeable delay, so may want to play it safe to include others that may take longer.

**Comment by kueblc** [comment]
That's great to hear you got it working!

Do I understand correctly that this also got your white channel working? Very strange that the change should impact the operation of the white channel at all.

I do still wonder what's going on with your white flashing on dim. Does this issue persist when using only GPIO05? If so, it's outside of the code I touched, and as I can't reproduce it, I'm at a loss.

**Comment by damondins** [comment]
@kueblc  Yes, the White channel is now working. I was also able to somewhat find why it wasn't working and why the change made a difference. When I went to do the 2nd bulb the white failed to turn on so I noticed an anomaly on the 1st bulb after updating to the dev branch it was set to module SP10 (67). So I changed to that on the 2nd bulb then changed back to the SYF05 module. Then Set the GPIO13 to the PWR and it started working. So on the 3rd bulb, it was still set to Generic with all the settings for the pins. I removed all the settings then updated to Tasmota sonoff minimal, then updated to the new firmware. Set the GPIO13 pin to PWR and all worked. So all I can think of is that there were settings getting stuck in the config that was causing the white to fail. 

I will have to look at the flashing issue further to determine that as I have moved the bulbs away from where my computer is at the moment. I'll work with that tonight at some point and let you know.

**Pull request merged**
